# Site settings
title: John Aspinall
email: john.aspinall73@gmail.com
url: https://example.github.io
description: "The peronal website, blog and portfolio of work for John Aspinall."
skills: "Front end developer - UX Designer - Podcaster "
meta_author: Aspinall John

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: 18bc9c #80B3FF
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2c3e50 #FD6E8A
  secondary-dark: 233140 #A2122F

# Footer settings
footer:
  copyright: John Aspinall
  location: Location
  social: Around the Web
  credits: My limited company

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/johnasp
  - title: linkedin
    url: https://www.linkedin.com/in/aspinalljohn/
  - title: codepen
    url: http://codepen.io/johnasp/
  - title: github
    url: https://github.com/johnasp

# Postal address (add as many lines as necessary)
address:
  - line: Poulton-le-Fylde
  - line: Lancashire, UK



# Build settings
markdown: kramdown
permalink: pretty

#tell Jekyll to no longer watch for Sass file changes or compile them
exclude: [‘css’, ‘_scss’, 'node_modules', 'package.json', 'gruntfile.js', 'README.md', 'LICENCE']
#tell Jekyll not to erase the CSS directory in the _site output folder 
keep_files: ['css']
